<?php 
$config['id'] = '1'; 
$config['dropbox_email'] = ''; 
$config['dropbox_password'] = ''; 
$config['site_contact_mail'] = 'baysideyardparties@gmail.com'; 
$config['site_contact_number'] = ''; 
$config['email_title'] = 'Beetrut'; 
$config['google_verification'] = '<meta name=\'google-site-verification\' content=\'qowARH6o-AgcUOo8pkV3jWgrD53GDYb1wRmQZE8L39k\' />'; 
$config['google_verification_code'] = '<script>
  (function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,\'script\',\'https://www.google-analytics.com/analytics.js\',\'ga\');

  ga(\'create\', \'UA-96611222-1\', \'auto\');
  ga(\'send\', \'pageview\');

</script>'; 
$config['google_redirect_url_db'] = 'http://www.beetrut.com/dbbackup/fileUpload.php '; 
$config['facebook_link'] = 'https://www.facebook.com/yardparties'; 
$config['twitter_link'] = ''; 
$config['tumblr_link'] = ''; 
$config['instagram_link'] = ''; 
$config['snapchat_link'] = ''; 
$config['pinterest'] = ''; 
$config['googleplus_link'] = ''; 
$config['linkedin_link'] = ''; 
$config['rss_link'] = ''; 
$config['youtube_link'] = 'https://www.youtube.com/channel/UCdM3eFY84wihPG47QQh5fjQ'; 
$config['footer_content'] = 'Copyright 2016. Beetrut. All rights reserved.'; 
$config['logo_image'] = 'smallLogo4.png'; 
$config['home_logo_image'] = 'smallLogo5.png'; 
$config['background_image'] = 'pool.jpg'; 
$config['under_construction_image'] = 'coming-soon.jpg'; 
$config['videoUrl'] = ''; 
$config['currency_type'] = 'USD'; 
$config['slider'] = 'on'; 
$config['meta_title'] = 'Venues for events, kids birthday. Artists & party rentals'; 
$config['meta_keyword'] = 'Venue for small events, kids birthdays, baby shower. Listing of party entertainers, jump houses, clowns'; 
$config['meta_description'] = 'Book local party venue for small events and kids birthdays. Listing of all unique places, activity and play areas. Hire party entertainers, planners and rent jump houses at cheaper prices'; 
$config['fevicon_image'] = 'smallLogo6.png'; 
$config['watermark'] = 'smallLogo7.png'; 
$config['facebook_api'] = ''; 
$config['facebook_secret_key'] = ''; 
$config['paypal_api_name'] = ''; 
$config['paypal_api_pw'] = ''; 
$config['paypal_api_key'] = ''; 
$config['authorize_net_key'] = ''; 
$config['paypal_id'] = ''; 
$config['paypal_live'] = ''; 
$config['smtp_port'] = '0'; 
$config['smtp_uname'] = ''; 
$config['smtp_password'] = ''; 
$config['consumer_key'] = ''; 
$config['consumer_secret'] = ''; 
$config['google_client_secret'] = '4e2c9cauPTY2Tds3tjPaPkE2'; 
$config['google_client_id'] = '44956486075-4jk2plb7792rbv1vmft542dlgpeu1cmq.apps.googleusercontent.com'; 
$config['google_redirect_url'] = 'http://www.beetrut.com/googlelogin/googleRedirect'; 
$config['google_redirect_url_connect'] = 'http://www.beetrut.com/site/invitefriend/google_connect'; 
$config['google_developer_key'] = 'AIzaSyCQBng0nlcWBDvm13vq92bVozZJwz_Ue30'; 
$config['linkedin_app_id'] = ''; 
$config['linkedin_app_id1'] = ''; 
$config['linkedin_app_key1'] = ''; 
$config['linkedin_app_key'] = ''; 
$config['facebook_app_id'] = '613707865487437'; 
$config['facebook_app_secret'] = '756351f7ab815b53ee016f325700b12f'; 
$config['like_text'] = 'Like'; 
$config['unlike_text'] = 'Unlike'; 
$config['liked_text'] = 'Like\'d'; 
$config['banner_text'] = ''; 
$config['site_pagination_per_page'] = '20'; 
$config['twilio_account_sid'] = ''; 
$config['twilio_account_token'] = ''; 
$config['twilio_phone_number'] = ''; 
$config['google_map_api'] = ' AIzaSyCQBng0nlcWBDvm13vq92bVozZJwz_Ue30'; 
$config['home_title_1'] = 'Host your next party'; 
$config['home_title_2'] = 'Find a perfect venue. Get artist entertainers'; 
$config['home_title_3'] = ''; 
$config['home_title_4'] = 'Venue checked. Balloons tied.'; 
$config['s3_bucket_name'] = ''; 
$config['s3_access_key'] = ''; 
$config['s3_secret_key'] = ''; 
$config['instagram'] = ''; 
$config['on_off'] = 'on'; 
$config['ios_link'] = ''; 
$config['android_link'] = ''; 
$config['created'] = '2017-03-29'; 
$config['modified'] = '2017-04-06'; 
$config['admin_name'] = 'yadmin'; 
$config['email'] = 'baysideyardparties@gmail.com'; 
$config['admin_type'] = 'super'; 
$config['privileges'] = ''; 
$config['last_login_date'] = '2017-04-06 12:36:24'; 
$config['last_logout_date'] = '2017-04-05 02:20:30'; 
$config['last_login_ip'] = '64.124.173.189'; 
$config['is_verified'] = 'Yes'; 
$config['status'] = 'Active'; 
$config['message_pagination_per_page'] = '10'; 
$config['base_url'] = 'http://www.beetrut.com/';  ?>