<?php 
$config['currency_id'] = '95'; 
$config['currency_contid'] = 'AS'; 
$config['currency_country_code'] = 'IN'; 
$config['currency_country_mobile_code'] = '+91'; 
$config['currency_name'] = 'India'; 
$config['currency_seourl'] = 'india'; 
$config['currency_currency_type'] = 'INR'; 
$config['currency_currency_symbol'] = '0'; 
$config['currency_shipping_cost'] = '15.00'; 
$config['currency_shipping_tax'] = '10.00'; 
$config['currency_meta_title'] = ''; 
$config['currency_meta_keyword'] = ''; 
$config['currency_meta_description'] = ''; 
$config['currency_description'] = ''; 
$config['currency_status'] = 'Active'; 
$config['currency_dateAdded'] = '2015-04-28 10:51:02'; 
$config['currency_currency_default'] = 'Yes'; 
$config['currency_slider_image'] = '0'; 
$config['currency_logo'] = '0'; 
$config['currency_map'] = '0'; 
$config['currency_thumb'] = ''; 
$config['currency_language_code'] = 'en';  ?>